language: python
env:
  matrix:
    - EMACS=emacs
    - EMACS=emacs24 EMACS_PPA=ppa:cassou/emacs
    - EMACS=emacs-snapshot EMACS_PPA=ppa:cassou/emacs
  global:
    - CASK=$HOME/.cask/bin/cask
matrix:
  allow_failures:
    - env: EMACS=emacs
    - env: EMACS=emacs-snapshot EMACS_PPA=ppa:cassou/emacs
before_install:
  - pip install -q flask tornado

  # Install Emacs
  - test -n "$EMACS_PPA" && sudo add-apt-repository -y "$EMACS_PPA"
  - sudo apt-get update -qq
  - sudo apt-get install -qq "$EMACS" "${EMACS}-el"

  # Install Cask
  - curl -fsSkL
        --max-time 10
        --retry 10
        --retry-delay 10
        https://raw.github.com/cask/cask/master/go
        | python
script:
  make travis-ci
